/**
 * R30: themes for whoever did not write one in time. pt-BR, fun and easy to draw; drawn without
 * repetition within a match.
 */
export const FALLBACK_THEMES: readonly string[] = [
  'Um gato que virou prefeito da cidade',
  'O dia em que choveu macarrão',
  'Um robô aprendendo a dançar forró',
  'A girafa que tinha medo de altura',
  'Um pirata perdido no supermercado',
  'O sorvete que não queria derreter',
  'Uma vaca astronauta na Lua',
  'O fantasma que tinha medo do escuro',
  'Um dinossauro na fila do banco',
  'A batalha final entre o garfo e a colher',
  'Um pinguim de férias na praia',
  'O mago que só fazia feitiços errados',
  'Uma tartaruga correndo uma maratona',
  'O dia em que os gatos aprenderam a falar',
  'Um alienígena provando feijoada',
  'A galinha que botou um ovo de ouro... e se arrependeu',
  'Um super-herói com poderes inúteis',
  'O cachorro que queria ser carteiro',
  'Uma festa de aniversário no fundo do mar',
  'O vampiro que só bebia suco de tomate',
  'Uma corrida de carrinhos de supermercado',
  'O elefante escondido atrás da cortina',
  'Um chef de cozinha que só sabe fazer ovo frito',
  'A planta carnívora que virou vegetariana',
  'Um polvo trabalhando como garçom',
  'O ladrão de meias da máquina de lavar',
  'Uma bruxa aprendendo a andar de skate',
  'O boneco de neve que foi ao deserto',
  'Um castelo feito de pudim',
  'A preguiça que ganhou na loteria',
  'Um unicórnio preso no trânsito',
  'O dia em que a gravidade tirou folga',
  'Um macaco consertando um computador',
  'A sereia que queria ser bombeira',
  'Um zumbi fazendo compras na feira',
  'O sapo que virou príncipe e se arrependeu',
  'Uma nave espacial movida a pastel',
  'O cavaleiro que tinha medo de cavalo',
  'Um tubarão no dentista',
  'A avó que é campeã de videogame',
  'Um ninja tentando ser silencioso numa loja de cristais',
  'O pato que montou uma banda de rock',
  'Uma viagem dentro de uma geladeira',
  'O caracol entregador de pizza',
  'Um urso que hiberna no escritório',
  'O espantalho que fez amizade com os corvos',
  'Uma minhoca que sonhava em voar',
  'O rei que perdeu a coroa na sopa',
];
